### ISSUE TITLE
haddock failure

### ISSUE THREAD

**Issue by bergmark** [fpinsight/hocilib#1]
Originally reported in the stackage PR, but that issue is closed.

The test-suite for this package has been disabled in stackage because of this issue. When a fix is published to hackage could you please send a PR to re-enable the haddocks to stackage (it's in the expected-haddock-failures section) or ping me?

Thanks!

```
Haddock coverage:
  50% (  1 /  2) in 'Database.Ocilib.Internal'
  Missing documentation for:
    toMaybePtr (src/Database/Ocilib/Internal.hs:16)
haddock: internal error: internal: extractDecl (ClassDecl)
CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:793:16 in main:Haddock.Interface.Create
```

**Comment by thierry-b** [comment]
Hi Adam, seems to be only happening with ghc8, i think it is related to default signature extension.
I'll send a PR when i get it fixed.
Thanks,
Thierry
